# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc395f7a60861115ff2e1c359b3f64f79c07aaa8b33283c0e5544251f3458c769e4141b864532ee2c519b10e53b304acfbeff5619d931be69aada5390eddb0d9

test:
  secret_key_base: 286858f5dd38a7ace7021babbc87f54a83404a28fc9632df86e08d186d183a87bab17cdd6a9c363c132806c4760ed638f8ddffbdcb0a255016ce2f62826109ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
